import os
import numpy as np
import torch
import SimpleITK as sitk

from monai.networks.nets import SegResNet
from monai.inferers import sliding_window_inference


# ============================================================
# PATHS
# ============================================================

# Project/code directory
PROJECT_DIR = r"C:\Users\chand\BrainTumorProject\Brain-Tumors-Segmentation"

# IMPORTANT:
# Your BraTS dataset is OUTSIDE the project directory.
DATASET_DIR = r"C:\Users\chand\BrainTumorProject\dataset"

# Trained SegResNet checkpoint
CHECKPOINT_PATH = os.path.join(
    PROJECT_DIR,
    "segres_net_runs",
    "best-model",
    "best-model.pkl"
)

# Folder where predictions generated by this script will be saved
OUTPUT_DIR = os.path.join(
    PROJECT_DIR,
    "user_predictions"
)


# ============================================================
# MODEL SETTINGS
# ============================================================

INPUT_SIZE = (128, 128, 128)

IN_CHANNELS = 4
NUM_CLASSES = 3

# RTX 3050 6GB safe setting
SW_BATCH_SIZE = 1

# Sliding-window overlap
INFER_OVERLAP = 0.5

# Probability threshold
THRESHOLD = 0.5


# ============================================================
# DEVICE
# ============================================================

DEVICE = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)


# ============================================================
# LOAD NIFTI
# ============================================================

def load_nii(path):
    """
    Load a NIfTI image using SimpleITK.

    Returns:
        array      : NumPy array in [Z, Y, X] format
        sitk_image : Original SimpleITK image
    """

    image = sitk.ReadImage(path)

    array = sitk.GetArrayFromImage(image)

    return array.astype(np.float32), image


# ============================================================
# NORMALIZE
# ============================================================

def minmax_normalize(image):
    """
    Percentile-based min-max normalization.

    Only non-zero MRI voxels are used to calculate
    the intensity range.
    """

    image = image.astype(np.float32)

    nonzero = image[image > 0]

    if len(nonzero) == 0:
        return image

    min_value = np.percentile(nonzero, 1)
    max_value = np.percentile(nonzero, 99)

    # Avoid division problems
    if max_value <= min_value:
        return image

    image = np.clip(
        image,
        min_value,
        max_value
    )

    image = (
        image - min_value
    ) / (
        max_value - min_value + 1e-8
    )

    return image


# ============================================================
# FIND NON-ZERO REGION
# ============================================================

def get_nonzero_bbox(image):
    """
    Find the bounding box containing non-zero MRI information.

    Input:
        image shape = [C, Z, Y, X]

    Returns:
        z_min, z_max,
        y_min, y_max,
        x_min, x_max
    """

    combined = np.sum(
        np.abs(image),
        axis=0
    )

    nonzero = np.argwhere(
        combined != 0
    )

    if nonzero.size == 0:

        return (
            0,
            image.shape[1],
            0,
            image.shape[2],
            0,
            image.shape[3]
        )

    z_min, y_min, x_min = nonzero.min(axis=0)

    z_max, y_max, x_max = nonzero.max(axis=0)

    # Include one voxel of surrounding area,
    # matching the existing preprocessing idea.
    z_min = max(
        0,
        int(z_min) - 1
    )

    y_min = max(
        0,
        int(y_min) - 1
    )

    x_min = max(
        0,
        int(x_min) - 1
    )

    z_max = min(
        image.shape[1],
        int(z_max) + 1
    )

    y_max = min(
        image.shape[2],
        int(y_max) + 1
    )

    x_max = min(
        image.shape[3],
        int(x_max) + 1
    )

    return (
        z_min,
        z_max,
        y_min,
        y_max,
        x_min,
        x_max
    )


# ============================================================
# CENTER CROP / PAD
# ============================================================

def center_crop_or_pad(
    image,
    target_size=(128, 128, 128)
):
    """
    Center crop or zero-pad a [C, Z, Y, X] image
    to exactly target_size.
    """

    channels, z, y, x = image.shape

    target_z, target_y, target_x = target_size

    # --------------------------------------------------------
    # Crop coordinates
    # --------------------------------------------------------

    z_start = max(
        0,
        (z - target_z) // 2
    )

    y_start = max(
        0,
        (y - target_y) // 2
    )

    x_start = max(
        0,
        (x - target_x) // 2
    )

    z_end = min(
        z,
        z_start + target_z
    )

    y_end = min(
        y,
        y_start + target_y
    )

    x_end = min(
        x,
        x_start + target_x
    )

    cropped = image[
        :,
        z_start:z_end,
        y_start:y_end,
        x_start:x_end
    ]

    # --------------------------------------------------------
    # Padding
    # --------------------------------------------------------

    current_z = cropped.shape[1]
    current_y = cropped.shape[2]
    current_x = cropped.shape[3]

    pad_z = max(
        0,
        target_z - current_z
    )

    pad_y = max(
        0,
        target_y - current_y
    )

    pad_x = max(
        0,
        target_x - current_x
    )

    pad_before_z = pad_z // 2
    pad_after_z = pad_z - pad_before_z

    pad_before_y = pad_y // 2
    pad_after_y = pad_y - pad_before_y

    pad_before_x = pad_x // 2
    pad_after_x = pad_x - pad_before_x

    padded = np.pad(
        cropped,
        (
            (0, 0),
            (pad_before_z, pad_after_z),
            (pad_before_y, pad_after_y),
            (pad_before_x, pad_after_x)
        ),
        mode="constant",
        constant_values=0
    )

    crop_info = {
        "z_start": z_start,
        "z_end": z_end,

        "y_start": y_start,
        "y_end": y_end,

        "x_start": x_start,
        "x_end": x_end,

        "pad_before_z": pad_before_z,
        "pad_after_z": pad_after_z,

        "pad_before_y": pad_before_y,
        "pad_after_y": pad_after_y,

        "pad_before_x": pad_before_x,
        "pad_after_x": pad_after_x,

        "original_shape": (z, y, x)
    }

    return padded, crop_info


# ============================================================
# RESTORE PREDICTION TO CROPPED REGION
# ============================================================

def restore_prediction(
    prediction,
    crop_info
):
    """
    Remove padding from the 128x128x128 prediction
    and restore it to the cropped MRI region.
    """

    # Original cropped-region dimensions
    cropped_z = (
        crop_info["z_end"]
        - crop_info["z_start"]
    )

    cropped_y = (
        crop_info["y_end"]
        - crop_info["y_start"]
    )

    cropped_x = (
        crop_info["x_end"]
        - crop_info["x_start"]
    )

    # Remove padding using the known crop dimensions.
    prediction = prediction[
        crop_info["pad_before_z"]:
        crop_info["pad_before_z"] + cropped_z,

        crop_info["pad_before_y"]:
        crop_info["pad_before_y"] + cropped_y,

        crop_info["pad_before_x"]:
        crop_info["pad_before_x"] + cropped_x
    ]

    original_z, original_y, original_x = (
        crop_info["original_shape"]
    )

    restored = np.zeros(
        (
            original_z,
            original_y,
            original_x
        ),
        dtype=np.uint8
    )

    restored[
        crop_info["z_start"]:
        crop_info["z_end"],

        crop_info["y_start"]:
        crop_info["y_end"],

        crop_info["x_start"]:
        crop_info["x_end"]
    ] = prediction

    return restored


# ============================================================
# CREATE LABEL MAP
# ============================================================

def create_label_map(probabilities):
    """
    Model output channels:

        Channel 0 = Enhancing Tumor (ET)
        Channel 1 = Tumor Core (TC)
        Channel 2 = Whole Tumor (WT)

    Convert to BraTS-style label map:

        0 = Background
        1 = NCR/NET
        2 = Edema
        3 = Enhancing Tumor

    Priority:

        ET > TC > WT
    """

    et = probabilities[0] > THRESHOLD

    tc = probabilities[1] > THRESHOLD

    wt = probabilities[2] > THRESHOLD

    label = np.zeros(
        et.shape,
        dtype=np.uint8
    )

    # Whole tumor / edema
    label[wt] = 2

    # Tumor core / NCR-NET
    label[tc] = 1

    # Enhancing tumor
    label[et] = 3

    return label


# ============================================================
# LOAD MODEL
# ============================================================

def load_model():
    """
    Create the same SegResNet architecture used by
    the trained checkpoint and load the weights.
    """

    print()
    print("=" * 70)
    print("LOADING SEGRESNET MODEL")
    print("=" * 70)

    print("Checkpoint:")
    print(CHECKPOINT_PATH)

    print()
    print("Device:")
    print(DEVICE)

    if torch.cuda.is_available():

        print(
            "GPU:",
            torch.cuda.get_device_name(0)
        )

    print("=" * 70)

    # --------------------------------------------------------
    # Check checkpoint
    # --------------------------------------------------------

    if not os.path.exists(CHECKPOINT_PATH):

        raise FileNotFoundError(
            "\nCheckpoint not found:\n"
            f"{CHECKPOINT_PATH}"
        )

    # --------------------------------------------------------
    # Create model
    # --------------------------------------------------------

    model = SegResNet(
        spatial_dims=3,
        init_filters=32,
        in_channels=IN_CHANNELS,
        out_channels=NUM_CLASSES,
        dropout_prob=0.2,
        blocks_down=(1, 2, 2, 4),
        blocks_up=(1, 1, 1)
    ).to(DEVICE)

    # --------------------------------------------------------
    # Load checkpoint
    # --------------------------------------------------------

    checkpoint = torch.load(
        CHECKPOINT_PATH,
        map_location=DEVICE,
        weights_only=True
    )

    # --------------------------------------------------------
    # Check checkpoint type
    # --------------------------------------------------------

    if not isinstance(checkpoint, dict):

        raise TypeError(
            "\nUnexpected checkpoint format.\n"
            f"Expected state_dict/dictionary, got: "
            f"{type(checkpoint)}"
        )

    # --------------------------------------------------------
    # Load weights
    # --------------------------------------------------------

    model.load_state_dict(
        checkpoint
    )

    model.eval()

    print()
    print("Model loaded successfully.")

    return model


# ============================================================
# RUN PREDICTION
# ============================================================

def predict_patient(patient_dir, model):
    """
    Run SegResNet inference for one BraTS patient.

    Required files:

        patient-t1n.nii.gz
        patient-t1c.nii.gz
        patient-t2w.nii.gz
        patient-t2f.nii.gz
    """

    patient_id = os.path.basename(
        os.path.normpath(patient_dir)
    )

    print()
    print("=" * 70)
    print("RUNNING INFERENCE")
    print("=" * 70)

    print("Patient:", patient_id)

    # --------------------------------------------------------
    # Required modalities
    # --------------------------------------------------------

    modality_names = [
        "t1n",
        "t1c",
        "t2w",
        "t2f"
    ]

    images = []

    reference_image = None

    # --------------------------------------------------------
    # Load all 4 modalities
    # --------------------------------------------------------

    for modality in modality_names:

        path = os.path.join(
            patient_dir,
            f"{patient_id}-{modality}.nii.gz"
        )

        if not os.path.exists(path):

            raise FileNotFoundError(
                "\nMissing MRI modality:\n"
                f"{path}"
            )

        image, sitk_image = load_nii(path)

        print(
            f"{modality.upper()} shape:",
            image.shape
        )

        if reference_image is None:
            reference_image = sitk_image

        images.append(image)

    # --------------------------------------------------------
    # Check dimensions
    # --------------------------------------------------------

    shapes = [
        image.shape
        for image in images
    ]

    if len(set(shapes)) != 1:

        raise ValueError(
            "\nMRI modalities have different shapes:\n"
            f"{shapes}"
        )

    # --------------------------------------------------------
    # Check spatial metadata
    # --------------------------------------------------------

    print()
    print("All 4 MRI modalities loaded successfully.")

    # --------------------------------------------------------
    # Stack modalities
    # --------------------------------------------------------

    image = np.stack(
        images,
        axis=0
    )

    print(
        "Combined MRI shape:",
        image.shape
    )

    # --------------------------------------------------------
    # Remove black border
    # --------------------------------------------------------

    bbox = get_nonzero_bbox(
        image
    )

    (
        z_min,
        z_max,
        y_min,
        y_max,
        x_min,
        x_max
    ) = bbox

    cropped_image = image[
        :,
        z_min:z_max,
        y_min:y_max,
        x_min:x_max
    ]

    print(
        "After black-area removal:",
        cropped_image.shape
    )

    # --------------------------------------------------------
    # Normalize each modality
    # --------------------------------------------------------

    for channel in range(
        cropped_image.shape[0]
    ):

        cropped_image[channel] = (
            minmax_normalize(
                cropped_image[channel]
            )
        )

    print("MRI normalization completed.")

    # --------------------------------------------------------
    # Center crop / pad
    # --------------------------------------------------------

    model_input, crop_info = (
        center_crop_or_pad(
            cropped_image,
            INPUT_SIZE
        )
    )

    print(
        "Model input shape:",
        model_input.shape
    )

    # --------------------------------------------------------
    # Tensor
    # --------------------------------------------------------

    tensor = torch.from_numpy(
        model_input
    ).float()

    # [C, Z, Y, X]
    # ->
    # [B, C, Z, Y, X]

    tensor = tensor.unsqueeze(0)

    tensor = tensor.to(
        DEVICE
    )

    # --------------------------------------------------------
    # Model inference
    # --------------------------------------------------------

    print()
    print("Running SegResNet...")
    print("Please wait...")

    if DEVICE.type == "cuda":

        torch.cuda.empty_cache()

    with torch.no_grad():

        logits = sliding_window_inference(
            inputs=tensor,
            roi_size=INPUT_SIZE,
            sw_batch_size=SW_BATCH_SIZE,
            predictor=model,
            overlap=INFER_OVERLAP
        )

        probabilities = torch.sigmoid(
            logits
        )

    # --------------------------------------------------------
    # Move prediction to CPU
    # --------------------------------------------------------

    probabilities = probabilities[
        0
    ].cpu().numpy()

    print(
        "Prediction probability shape:",
        probabilities.shape
    )

    # --------------------------------------------------------
    # Convert probabilities to labels
    # --------------------------------------------------------

    prediction = create_label_map(
        probabilities
    )

    print(
        "Prediction label shape:",
        prediction.shape
    )

    # --------------------------------------------------------
    # Restore prediction to cropped region
    # --------------------------------------------------------

    prediction_cropped = restore_prediction(
        prediction,
        crop_info
    )

    # --------------------------------------------------------
    # Restore to original MRI dimensions
    # --------------------------------------------------------

    original_shape = images[0].shape

    full_prediction = np.zeros(
        original_shape,
        dtype=np.uint8
    )

    full_prediction[
        z_min:z_max,
        y_min:y_max,
        x_min:x_max
    ] = prediction_cropped

    # --------------------------------------------------------
    # Detection
    # --------------------------------------------------------

    tumor_voxels = int(
        np.sum(
            full_prediction > 0
        )
    )

    edema_voxels = int(
        np.sum(
            full_prediction == 2
        )
    )

    ncr_voxels = int(
        np.sum(
            full_prediction == 1
        )
    )

    et_voxels = int(
        np.sum(
            full_prediction == 3
        )
    )

    tumor_detected = (
        tumor_voxels > 0
    )

    # --------------------------------------------------------
    # Segmentation confidence
    # --------------------------------------------------------
    # Confidence is calculated from the model probability map
    # for voxels assigned to the final tumor segmentation.
    # This is a model-derived confidence indicator, not a
    # clinically validated diagnostic probability.
    tumor_confidence = 0.0

    if tumor_voxels > 0:
        assigned_probabilities = np.zeros(
            prediction.shape,
            dtype=np.float32
        )

        # ET -> channel 0
        et_mask = prediction == 3
        assigned_probabilities[et_mask] = probabilities[0][et_mask]

        # NCR/NET (TC-only) -> channel 1
        ncr_mask = prediction == 1
        assigned_probabilities[ncr_mask] = probabilities[1][ncr_mask]

        # Edema (WT-only) -> channel 2
        edema_mask = prediction == 2
        assigned_probabilities[edema_mask] = probabilities[2][edema_mask]

        cropped_tumor_mask = prediction > 0
        tumor_confidence = float(
            np.mean(
                assigned_probabilities[cropped_tumor_mask]
            ) * 100.0
        )

    # --------------------------------------------------------
    # Results
    # --------------------------------------------------------

    print()
    print("=" * 70)
    print("PREDICTION RESULT")
    print("=" * 70)

    print()

    if tumor_detected:

        print("RESULT: TUMOR DETECTED")

    else:

        print("RESULT: NO TUMOR DETECTED")

    print()
    print("Tumor voxels:", tumor_voxels)
    print("Edema voxels:", edema_voxels)
    print("NCR/NET voxels:", ncr_voxels)
    print("Enhancing tumor voxels:", et_voxels)

    print("=" * 70)

    # --------------------------------------------------------
    # Save prediction
    # --------------------------------------------------------

    os.makedirs(
        OUTPUT_DIR,
        exist_ok=True
    )

    output_path = os.path.join(
        OUTPUT_DIR,
        f"{patient_id}-prediction.nii.gz"
    )

    # Create NIfTI image
    prediction_image = sitk.GetImageFromArray(
        full_prediction
    )

    # Preserve MRI spatial information
    prediction_image.CopyInformation(
        reference_image
    )

    # Save
    sitk.WriteImage(
        prediction_image,
        output_path
    )

    print()
    print("Prediction saved:")
    print(output_path)

    print()

    return {
        "patient_id": patient_id,

        "tumor_detected": tumor_detected,

        "tumor_voxels": tumor_voxels,

        "edema_voxels": edema_voxels,

        "ncr_voxels": ncr_voxels,

        "enhancing_tumor_voxels": et_voxels,

        "tumor_confidence": tumor_confidence,

        "prediction": full_prediction,

        "probabilities": probabilities,

        "mri": images[0],

        "reference_image": reference_image
    }


# ============================================================
# MAIN TEST
# ============================================================

if __name__ == "__main__":

    # --------------------------------------------------------
    # TEST PATIENT
    # --------------------------------------------------------
    #
    # This patient already exists in your BraTS 2023
    # test dataset.
    #
    # IMPORTANT:
    # Dataset path comes from DATASET_DIR, NOT PROJECT_DIR.
    # --------------------------------------------------------

    TEST_PATIENT_ID = "BraTS-GLI-00002-000"

    TEST_PATIENT_DIR = os.path.join(
        DATASET_DIR,
        "brats2023",
        "test",
        TEST_PATIENT_ID
    )

    print()
    print("=" * 70)
    print("SEGRESNET SINGLE-PATIENT INFERENCE TEST")
    print("=" * 70)

    print()
    print("Project directory:")
    print(PROJECT_DIR)

    print()
    print("Dataset directory:")
    print(DATASET_DIR)

    print()
    print("Checkpoint:")
    print(CHECKPOINT_PATH)

    print()
    print("Patient folder:")
    print(TEST_PATIENT_DIR)

    # --------------------------------------------------------
    # Verify project directory
    # --------------------------------------------------------

    if not os.path.exists(PROJECT_DIR):

        raise FileNotFoundError(
            "\nProject directory not found:\n"
            f"{PROJECT_DIR}"
        )

    # --------------------------------------------------------
    # Verify dataset directory
    # --------------------------------------------------------

    if not os.path.exists(DATASET_DIR):

        raise FileNotFoundError(
            "\nDataset directory not found:\n"
            f"{DATASET_DIR}"
        )

    # --------------------------------------------------------
    # Verify patient folder
    # --------------------------------------------------------

    if not os.path.exists(TEST_PATIENT_DIR):

        raise FileNotFoundError(
            "\nPatient folder not found:\n"
            f"{TEST_PATIENT_DIR}\n\n"
            "Expected structure:\n"
            f"{DATASET_DIR}\\brats2023\\test\\"
            f"{TEST_PATIENT_ID}"
        )

    # --------------------------------------------------------
    # Load model
    # --------------------------------------------------------

    model = load_model()

    # --------------------------------------------------------
    # Run inference
    # --------------------------------------------------------

    result = predict_patient(
        TEST_PATIENT_DIR,
        model
    )

    # --------------------------------------------------------
    # Final message
    # --------------------------------------------------------

    print()
    print("=" * 70)
    print("INFERENCE COMPLETED SUCCESSFULLY")
    print("=" * 70)

    print()
    print("Patient:", result["patient_id"])

    if result["tumor_detected"]:

        print("Final result: TUMOR DETECTED")

    else:

        print("Final result: NO TUMOR DETECTED")

    print()
    print("Prediction file:")
    print(
        os.path.join(
            OUTPUT_DIR,
            f"{result['patient_id']}-prediction.nii.gz"
        )
    )

    print("=" * 70)